<?php if (empty($_POST['menu'])) { ?>
<html>
<head>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

	<link rel="stylesheet" type="text/css" href="../fileadmin/css/style.css">
    <!-- Begin emoji-picker Stylesheets -->
    <link href="../fileadmin/css/emoji.css" rel="stylesheet">
    <!-- End emoji-picker Stylesheets -->
	
	<!-- Begin emoji-picker JavaScript -->
    <script src="../fileadmin/js/config.js"></script>
    <script src="../fileadmin/js/util.js"></script>
    <script src="../fileadmin/js/jquery.emojiarea.js"></script>
    <script src="../fileadmin/js/emoji-picker.js"></script>
    

</head>
<body>
	
	<script src="../fileadmin/js/tools.js"></script>
	<script>
      $(function() {
        // Initializes and creates emoji set from sprite sheet
        window.emojiPicker = new EmojiPicker({
          emojiable_selector: '[data-emojiable=true]',
          assetsPath: '../fileadmin/img/',
          popupButtonClasses: 'fa fa-smile-o'
        });
        // Finds all elements with `emojiable_selector` and converts them to rich emoji input fields
        // You may want to delay this step if you have dynamically created input fields that appear later in the loading process
        // It can be called as many times as necessary; previously converted input fields will not be converted again
        window.emojiPicker.discover();
      });

      // Google Analytics
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-49610253-3', 'auto');
      ga('send', 'pageview');
    </script>
	
	<ul class="menu cf">
		<li>
			<a href="">Block</a>
			<ul class="submenu">
				<li class="li_menu" data-section="block" data-action="list"><a href="javascript:void(0);">List</a></li>
				<li class="li_menu" data-section="block" data-action="detail"><a href="javascript:void(0);">Detail</a></li>
				<li class="li_menu" data-section="block" data-action="detail" data-create="1"><a href="javascript:void(0);" id="11create_block">Create</a></li>
			</ul>
		</li>
		<li>
			<a href="">Tags</a>
			<ul class="submenu">
				<li class="li_menu" data-section="tags" data-action="list"><a href="javascript:void(0);">List</a></li>
				<li class="li_menu" data-section="tags" data-action="edit"><a href="javascript:void(0);">Edit</a></li>
			</ul>			
		</li>
		<!--
		<li>
			<a href="">Keyboard</a>
			<ul class="submenu">
				<li class="li_menu" data-section="keyboard" data-action="list"><a href="javascript:void(0);">List</a></li>
				<li class="li_menu" data-section="keyboard" data-action="edit"><a href="javascript:void(0);">Edit</a></li>
			</ul>
		</li>
		-->
	</ul>

	<div class="all_actions">
<?php
	}

	include '../db/connection.php';
    include '../db/query.php';
    include 'logic.php';
	
	if ($_POST['menu']) {
		include $_POST['section'] . '/' . $_POST['action'] . '.phtml';
	}
	if (empty($_POST['menu'])) { 
?>
	</div>

	</body>
</html>
<?php } ?>